[package]
name = "lifec_registry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgui = "0.8.2"
lifec = { git = "https://github.com/juliusl/lifec.git", branch = "main" }
lifec_poem = { git = "https://github.com/juliusl/lifec_poem.git", branch = "main" }
poem = { version = "1.3.32", features = ["server", "static-files", "rustls", "test"] }
serde = "1.0"
tokio = "1.20.1"
tracing = "0.1.35"
tracing-subscriber =  { version = "0.3", features = [ "env-filter" ] }
