name: Rust

on:
  push:
    branches: [ "main" ]
    tags: v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Install tools
      run: cargo install cargo-deb
    - name: Package
      run: cargo deb
    - name: Copy Artifacts
      run: |
        mkdir out
        cp target/debian/*.deb out/
        ls out
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: out/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
